### ISSUE TITLE
Publisher is showing as consumer and consumer is showing producer on UI

### ISSUE THREAD

**Issue by 19941112** [springwolf/springwolf-core#148] opened 2023-02-23 05:21 UTC
**Describe the bug**
when running the publisher app on UI it is showing consumer on Channels tab and the same for consumer as well it is showing producer
Added screenshots for reference.

**Dependencies and versions used**
attached screenshot for dependencies added

**Code example**

**Stack trace and error logs**
N/A
![image](https://user-images.githubusercontent.com/50715301/220826752-c83b05db-55bf-4653-a1c3-28973134b2ca.png)
![image](https://user-images.githubusercontent.com/50715301/220826808-0253f24e-9ed8-48c1-99a7-8ad1f5521d87.png)
![image](https://user-images.githubusercontent.com/50715301/220827025-62e4642c-fe87-4bf4-8851-9c612ba0e350.png)

**Comment by sam0r040** [comment] 2023-02-24 14:57
Hi, you are using some old versions. The current version of the amqp plugin and the springwolf-ui is 0.6.0. Can you reproduce the issue with the current versions?

**Comment by sam0r040** [comment] 2023-02-27 17:41
Sorry, I don't understand your question. Is your problem that there are no headers documented or that there is this HeadersNotDocumented schema?

**Comment by 19941112** [comment] 2023-02-27 17:45
> Sorry, I don't understand your question. Is your problem that there are no headers documented or that there is this HeadersNotDocumented schema?

where do we need to configure to get headers in both the places?

**Comment by timonback** [comment] 2023-03-12 19:27
Hi, I dont know what kind of configuration you are using, but I am assuming that you use the plain `RabbitListener` annotation without any extras.

To tell springwolf about your headers, you will have to manually configure them.
The springwolf-amqp plugin (`AmqpProducerData` and `AmqpConsumerData`) does not support headers, which is fixed with https://github.com/springwolf/springwolf-core/pull/154.

Till then, you can use the AsyncListener and AsyncPublisher annotation.
Please refer the documentation for more details: https://springwolf.github.io/docs/documenting-consumers

**Comment by timonback** [comment] 2023-04-23 10:49
Closing due to inactivity.

**Closed by timonback** 2023-04-23 10:49 UTC
Labels: bug, waiting for feedback
