### ISSUE TITLE
AsyncApiDocket bean deprecation

### ISSUE THREAD

**Issue by sam0r040** [springwolf/springwolf-core#445] opened 2023-11-10 13:58 UTC
Dear users of Springwolf, 

after the deprecation of the `AsyncApiDocket` bean, some people have already asked us about migration options for their use cases.
Therefore, we will gather all information about it in this issue. We will try to address your concerns before we remove the `AsyncApiDocket` bean.

_If you have questions please add a comment and link._

**1. Add mandatory properties to application properties**

```Properties
springwolf.docket.base-package=io.github.stavshamir.springwolf.example.consumers

springwolf.docket.info.title=${spring.application.name}
springwolf.docket.info.version=1.0.0

springwolf.docket.servers.kafka.protocol=kafka
springwolf.docket.servers.kafka.url=${kafka.bootstrap.servers:localhost:29092}
```

Source: https://www.springwolf.dev/docs/quickstart

Map all entries of the docket to its Spring properties equivalent. The Spring properties equivalent start with `springwolf.docket..`
Example: The title within the info object is `springwolf.docket.info.title=my title`

**2. Convert consumers and/or producers to annotations**

Consumers and/or producers defined in the AsyncApiDocket have to be converted to the `@AsyncListener` and/or `@AsyncPublisher` annotation approach. See the Consumers and Producers page on how to map the properties.

* https://www.springwolf.dev/docs/configuration/documenting-consumers
* https://www.springwolf.dev/docs/configuration/documenting-producers

You can use the Spring Expression language to look up values from application properties at runtime. For example: 
```JAVA
@AsyncPublisher(
     operation = @AsyncOperation(
            channelName = "${spring.application.name}", //put variable here
            description = "More details for the outgoing topic"
     )
)
@KafkaAsyncOperationBinding
public void send(@Nonnull final String message) {
     send(message, Collections.emptyList());
}
```

Technically, it does not matter on which method you put those annotations. If you do not have an explicit method for consuming/producing, you can put the annotation on any method you like. Just make sure you specify the `payloadType` property.

**Comment by timonback** [comment] 2023-11-10 14:03
Related: https://github.com/springwolf/springwolf-core/issues/64#issuecomment-1792981038

**Comment by hirth-abi** [comment] 2023-11-12 15:05
I could migrate successfully to the new annotation based approach, thanks for the hints in this ticket. It would be nice if also subpackages within the `base-package` would be scanned, since our consumers/producers are in subpackages and I had to add several methods in the base package just for documentation.

**Comment by jenarp** [comment] 2023-11-15 07:13
I've noticed that Springwolf annotations are recognized only when they are placed within classes annotated with `@Component`,` @Service`, and similar. 
However, the class that contains my `send()` method, which I want to document with `@AsyncPublisher`, lacks such annotations. Instead, this class is instantiated via a `@Bean` definition in a `@Configuration` class. Consequently, it is not detected by the Component Scanner. 
I'm uncertain whether this is a unique issue with my application or a broader problem. It would be great if this could be addressed in the next release, as currently, I am unable to utilize Springwolf effectively. 
The only workaround seems to be customizing my Async API specification manually with `AsyncApiCustomizer`.

**Comment by hirth-abi** [comment] 2023-11-16 17:24
> All packages below and including `base-package` are scanned. Each of our examples projects find the producers/consumers in the sub-package `consumers` and `producers` respectively. Do you have an example so we can replicate it?

You're right, I've found the configuration error on my side 👍 

I've detected a minor issue, if we implement interfaces and document them, an unexpected documentation is also added for the interface method (an easy workaround is to define the `payloadType` redundantly). Here is an example: https://github.com/springwolf/springwolf-core/commit/bfd9f1702edba0c45a2557bdc2163f064cf046fb

**Comment by timonback** [comment] 2023-11-17 17:56
Hi @hirth-abi,
@sam0r040 and me looked into it and addressed it in #463 

Hi @jenarp,
we created #462 to track your suggestion

**Comment by silentrobi** [comment] 2023-12-05 22:36
We are having problem generating document when updating springwolf library bacause of our recent migration to 3.1.x. 
In our project a custom generic abstract class  is being used which is extended by other classes and the abstract class has core sendPublish method. As the abstract class  is not annotated with spring @Component, Springwolf-kafka can't detect @AsyncPublisher annotation which is very annoying. This will force us to change the core implementation. Besides, generated publishers through AsyncApiDocket (second approach) doesn't seems to be working  anymore. springwolf-ui doesn't show all the publishers and missing other information.
_springwolf-kafka & springwolf-ui --> 0.17.0_
<img width="929" alt="Untitled" src="https://github.com/springwolf/springwolf-core/assets/47764540/345dd643-2e67-44b4-a03b-6fa6ce959080">

**Comment by timonback** [comment] 2023-12-06 06:10
Hi @silentrobi 

> In our project a custom generic abstract class  is being used which is extended by other classes and the abstract class has core sendPublish method. As the abstract class  is not annotated with spring `@Component`, Springwolf-kafka can't detect @AsyncPublisher annotation which is very annoying.

We recently improved the handling of detecting on interfaces in #475
Can you try the current `-snapshot` version or adapt one of the example projects so that we can reproduce it?

> springwolf-ui doesn't show all the publishers and missing other information.

Is the `@KafkaAsyncOperationBinding` missing? https://www.springwolf.dev/docs/configuration/documenting-bindings
An excerpt from the asyncapi.json/yaml channels section would help.

**Comment by timonback** [comment] 2023-12-09 15:36
Yesterday, we also resolved the second outstanding limitation #462 (detect annotations in classes that are instantiated via `@Bean` methods in `@Configuration` classes).

@jenarp, @hirth-abi Feel free to try the current `-SNAPSHOT` build to verify and let us know whether something is missing.

**Comment by jenarp** [comment] 2023-12-14 13:51
Hi @timonback,
it works! My `@AsyncPublisher` annotation is scanned, now!
Thx for your effort!

**Comment by hirth-abi** [comment] 2023-12-15 15:50
Hi @timonback 0.17.0 was already working fine and the snapshot continues to do so. 

Perhaps just a question, I wanted to add the first time a description to a message, and `@AsyncOperation.description` seems to be ignored (for consumers and publishers, in the generated JSON file and the UI), is this currently expected?

**Comment by timonback** [comment] 2023-12-15 17:50
Great to hear.

That would be a bug if the description is ignored.
In our example, it seems to work: springwolf-examples/springwolf-kafka-example/src/main/java/io/github/stavshamir/springwolf/example/kafka/producers/NestedProducer.java

**Comment by timonback** [comment] 2024-03-02 07:59
1.0.0 does not contain the AsyncApiDocket anymore.
More details on how to migrate are documented in the gh release notes.

Feel free to open an issue, if you encounter any issues.

**Closed by timonback** 2024-03-02 07:59 UTC
Labels: staged for release
