### ISSUE TITLE
Spring Kafka - get consumers using @KafkaListener on a class and @KafkaHandler on 

### ISSUE THREAD

**Issue by meambobbo** [springwolf/springwolf-core#39] opened 2022-01-26 19:11 UTC
Our services typically have used @KafkaListener on the class declaration and @KafkaHandler on the method declarations within those classes. Springwolf-kafka does not seem to pick these up. I modified the code in one of my handler classes to only use @KafkaListener on the method declarations, and springwolf picks them up correctly.

I don't know whether this is considered an enhancement or a bug, but it'd be super nifty if this worked either way.

**Comment by stavshamir** [comment] 2022-01-26 20:03
Hi @meambobbo, thanks for opening the issue!
This is not a bug, simply was not implemented. Now that I see there is some demand, I can add it.

**Comment by meambobbo** [comment] 2022-01-27 03:51
I was toying around with the code and I have a solution that works for me. I'll put it in a fork and send a PR so you can see what I did, but you may choose to reject. For my case, we are doing things like this typically:

```
@Component
@RequiredArgsConstructor
@KafkaListener(
    groupId = "business-vessel-inventory-handler",
    topics = {
        EventManagerConstants.VESSEL_EVENTS_TOPIC
    }
)
public class VesselEventsHandler {

    @KafkaHandler
    public void onVesselDailyCloseGeneratedEvent(VesselDailyCloseGeneratedEvent event) {
         ...
    }

    @KafkaHandler
    public void onVesselVesselSaveEvent(VesselSaveEvent event) {
      ...
    }

    @KafkaHandler
    public void onVesselInventoryEvent(VesselInventoryEvent event) {
      ...
    }
}
```

We may have another class that also listens to the same topic with a different consumer group id and sometimes a different container factory with different properties.

The issue I ran into by trying to get doc on each @KafkaHandler method above was a duplicate channel name for the binding map. I have to append the group id AND the method name to the channel name to get unique entries. I like this, because the schema for the payload events in each handler are different, and I find it's very easy to see all my consumers in my services this way. I'm less familiar with AsyncApi, so I'm not sure if this bastardizes its intent conceptually.

**Comment by meambobbo** [comment] 2022-01-27 05:38
been looking at the spec - looks like the multiple event types is handled via `oneOf` key in the Message Object: https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#messageObject. This is clearly a better approach than to make each handler method represented as its own channel.

Not sure about the multiple listeners for the same topic case - I don't think AsyncApi allows multiple bindings.

I think the crux of the problem here is I want to use this documentation for internal purposes rather than as an external publisher/subscriber. If I'm external, I probably don't care which consumer group is subscribed to the events I'm publishing. and AsyncApi appears to be geared towards the external publish vs. internal doc.

**Comment by stavshamir** [comment] 2022-01-27 07:17
Hi @meambobbo, great input and a PR would be  very welcome, thanks for that.
I agree that `oneOf` is the fitting solution here. 
Also, AsyncApi does not allow multiple binding, but the [operation binding for kafka](https://github.com/asyncapi/bindings/blob/master/kafka/README.md#operation-binding-object) allows for multiple group ids to be provided. It may not be the best solution for you, because this way if different payloads are directed to different group ids, this can't be told in the documented.
However, if your different listeners with different consumer groups are in different microservices, a document can be produced for each one.

About the implementation - I don't have support for `oneOf` in the UI yet, so this may require some work. To support a class level listener, please create a class `ClassLevelKafkaListenerChannelScanner`. If you have any question or need guidance, please let me know!

**Comment by NeoScaler** [comment] 2022-02-07 11:45
We are also only using class-level @KafkaListener and @KafkaHandler on the method declarations. Hopefully this gets implemented soon. Keep up the good work.

**Comment by sshemirani** [comment] 2022-02-23 06:05
Is this going to be implemented? We really need this.

**Comment by stavshamir** [comment] 2022-02-23 08:29
@sshemirani @NeoScaler Thanks for the interest, I do hope to implement this. If anyone would like to contribute, that would be more than welcome.

**Comment by stavshamir** [comment] 2022-03-05 15:41
Just wanted to let anyone interested know that this is in progress an will be released in the coming weeks.

**Comment by stavshamir** [comment] 2022-03-23 10:13
Thanks for the patience, this is now released in 0.4.0. You should also update your UI version to 0.4.0.
If anyone would like to provide a small but helpful contribution related to this issue, please take a look at #50.

**Comment by NeoScaler** [comment] 2022-03-24 05:48
> Thanks for the patience, this is now released in 0.4.0. You should also update your UI version to 0.4.0.
> If anyone would like to provide a small but helpful contribution related to this issue, please take a look at #50.

Thanks a lot. I can see the docs after upgrading to the mentioned versions. UI is still empty and showing nothing unfortunately.

**Comment by stavshamir** [comment] 2022-03-24 06:04
Could you attach the docs please?

**Comment by NeoScaler** [comment] 2022-03-24 12:41
> Could you attach the docs please?

Unfortunately not, as it is company-owned code. The docs consist of 4 channels with each a published kafka binding and 1-2 messages each channel. The docs is shown as valid in the AsyncAPI Studio.

**Comment by stavshamir** [comment] 2022-04-03 09:13
I checked again and (as sad as I am to write it) it works on my machine with the basic example I created. It would be hard to debug without seeing the input, so if there is someway you could provide maybe a redacted example of the doc you have, I may be able to further investigate it.

**Comment by sshemirani** [comment] 2022-04-05 07:19
Thank you for your quick response. 
In order to re-produce the issue with the headers, you need to have two @KafkaHandler with two different payload types (The events should be java POJOs) on the same topic. The __TypeId__ header allows the spring to distinguish the method call depending on the incoming event.

Unfortunately I haven't had time to create a PoC for you.
Thanks a lot

**Comment by stavshamir** [comment] 2022-04-07 11:52
@sshemirani Thanks, I reproduced your problem and will try to solve it, I was referring to @NeoScaler in my last comment.

**Comment by NeoScaler** [comment] 2022-04-13 08:48
> I checked again and (as sad as I am to write it) it works on my machine with the basic example I created. It would be hard to debug without seeing the input, so if there is someway you could provide maybe a redacted example of the doc you have, I may be able to further investigate it.

I try to add a redacted example beginning next week.

**Comment by stavshamir** [comment] 2022-05-03 17:06
I'm closing this as I can't reproduce it and it seems to work for other people. Please open a new issue if your problem persists.

**Closed by stavshamir** 2022-05-03 17:06 UTC
Labels: enhancement
