### ISSUE TITLE
Springwolf-Kafka Protobuf Exception

### ISSUE THREAD

**Issue by kaant2** [springwolf/springwolf-core#341] opened 2023-08-31 07:56 UTC
**Describe the bug**
When working with protobufs, ExampleJsonGenerator class throws NullPointerException for type `google.protobuf.Timestamp`

**Dependencies and versions used**
`springwolf-kafka` version `0.13.0`.
`spring-boot` version `3.1.2`

**Code example**
 
`syntax = "proto3";
message AProto {
  string a = 1;
  string b = 2;
  string c = 3;
  string d = 4;
  google.protobuf.Timestamp e = 5;
  int64 f = 6;
  string g = 7;
}`

**Stack trace and error logs**

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springwolfInitApplicationListener' defined in URL [jar:file:/C:/Users/kaan/.m2/repository/io/github/springwolf/springwolf-core/0.13.0/springwolf-core-0.13.0.jar!/io/github/stavshamir/springwolf/asyncapi/SpringwolfInitApplicationListener.class]: Error occured during creation of AsyncAPI
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at com.aselsan.rehis.remiks.starter.common.factory.TimedDefaultListableBeanFactory.doGetBean(TimedDefaultListableBeanFactory.java:67)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at com.aselsan.rehis.remiks.starter.common.util.ApplicationSupport.run(ApplicationSupport.java:20)
	at com.aselsan.rehis.remiks.file.FileServiceApplication.main(FileServiceApplication.java:11)
Caused by: java.lang.RuntimeException: Error occured during creation of AsyncAPI
	at io.github.stavshamir.springwolf.asyncapi.DefaultAsyncApiService.getAsyncAPI(DefaultAsyncApiService.java:45)
	at io.github.stavshamir.springwolf.asyncapi.SpringwolfInitApplicationListener.afterPropertiesSet(SpringwolfInitApplicationListener.java:39)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	... 16 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "properties" is null
	at io.github.stavshamir.springwolf.schemas.example.ExampleJsonGenerator.handleObject(ExampleJsonGenerator.java:134)
	at io.github.stavshamir.springwolf.schemas.example.ExampleJsonGenerator.buildSchema(ExampleJsonGenerator.java:69)
	at io.github.stavshamir.springwolf.schemas.example.ExampleJsonGenerator.buildSchema(ExampleJsonGenerator.java:61)
	at io.github.stavshamir.springwolf.schemas.example.ExampleJsonGenerator.lambda$handleObject$0(ExampleJsonGenerator.java:140)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.github.stavshamir.springwolf.schemas.example.ExampleJsonGenerator.handleObject(ExampleJsonGenerator.java:144)
	at io.github.stavshamir.springwolf.schemas.example.ExampleJsonGenerator.buildSchema(ExampleJsonGenerator.java:69)
	at io.github.stavshamir.springwolf.schemas.example.ExampleJsonGenerator.buildSchema(ExampleJsonGenerator.java:61)
	at io.github.stavshamir.springwolf.schemas.example.ExampleJsonGenerator.lambda$handleObject$0(ExampleJsonGenerator.java:140)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.github.stavshamir.springwolf.schemas.example.ExampleJsonGenerator.handleObject(ExampleJsonGenerator.java:144)
	at io.github.stavshamir.springwolf.schemas.example.ExampleJsonGenerator.buildSchema(ExampleJsonGenerator.java:69)
	at io.github.stavshamir.springwolf.schemas.example.ExampleJsonGenerator.fromSchema(ExampleJsonGenerator.java:39)
	at io.github.stavshamir.springwolf.schemas.DefaultSchemasService.generateExampleWhenMissing(DefaultSchemasService.java:89)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at io.github.stavshamir.springwolf.schemas.DefaultSchemasService.finalizeDefinitions(DefaultSchemasService.java:45)
	at io.github.stavshamir.springwolf.schemas.DefaultSchemasService.getDefinitions(DefaultSchemasService.java:39)
	at io.github.stavshamir.springwolf.asyncapi.DefaultAsyncApiService.initAsyncAPI(DefaultAsyncApiService.java:71)
	at io.github.stavshamir.springwolf.asyncapi.DefaultAsyncApiService.getAsyncAPI(DefaultAsyncApiService.java:39)
	... 19 common frames omitted

`

**Comment by timonback** [comment] 2023-09-01 14:18
Hi @kaant2,

Thank you for the report.

Luckily, this is a duplicate of https://github.com/springwolf/springwolf-core/issues/314 and has been fixed in the current `-SNAPSHOT` version.

We do not use protobuf (google.protobuf.Timestamp) in this project, but like to support it/fix issues when there is an easy way.

I keep this open until the next release.
Feel free to re-open & comment if the issue persists in the next release.

**Comment by timonback** [comment] 2023-09-02 20:54
Thank your for the report, the issue has been addressed in the new release.

Feel free to reopen this issue if there is still something missing.

**Closed by timonback** 2023-09-02 20:54 UTC
Labels: bug, staged for release
